spring:
  datasource:
    url: jdbc:mysql://rm-uf668ux4p0c3o3lj2.mysql.rds.aliyuncs.com:3306/db_retail?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: jinguanjia
    password: ZDtGhnozcK1H1D
  output:
    ansi:
      enabled: always
site:
  staticServer: http://zkh-cdn.xyes.club/retail
  staticFilePath: /www/wwwroot/static/retail
wx:
  keyFile: /root/retail/weixinkey.p12
  keyPassword: 1538466881
logging:
  level:
    club.xyes.zkh.retail: info