spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_monolithiot_retail?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 942698@xyes
  output:
    ansi:
      enabled: always
site:
  staticServer: http://static0.berrontech.com/wechat
  staticFilePath: /var/www/static0.berrontech.com/wechat
wx:
  keyFile: /opt/wechat/weixinkey.p12
  keyPassword: 1538466881
logging:
  level:
    club.xyes.zkh.retail: info