server:
  port: 8003
spring:
  profiles:
    active: @activationProfile@
  application:
    name: e-commerce-api
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
pagehelper:
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:mappers/*.mapper.xml
  type-aliases-package: club.xyes.zkh.retail.common.entity
wx:
  appId: wx62f498b5f0e523fb
  secret: 0467d8f75e559660d8f2d64a56cb72ce
  mchId: 1540413381
  ip: 47.96.151.141
  notifyUrl: http://wxapi.berrontech.com/service/pay/notify
  refundNotifyUrl: http://wechat.berrontech.com/service/api/open/refund/notify
  signKey: 96e79218965eb72c92a549dd5a330112
sms:
  apiKey: 472dde7539dfb2c0ea2107be4d34dc63