spring:
  datasource:
    url: jdbc:mysql://192.168.2.100:3306/db_monolithiot_retail?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 156001
  output:
    ansi:
      enabled: always
site:
  staticServer: http://static0.xbb.com/retail
  staticFilePath: /var/www/nginx/retail
wx:
  keyFile: /opt/dev-service/retail/key/weixinkey.p12
  keyPassword: 1538466881
logging:
  level:
    club.xyes.zkh.retail: debug