spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_monolithiot_retail?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 156001
  output:
    ansi:
      enabled: always
site:
  staticServer: http://static.xbb.com/retail
  staticFilePath: D:\xbb\static\retail
wx:
  keyFile: E:\xbb\retail\weixinkey.p12
  keyPassword: 1538466881
logging:
  level:
    club.xyes.zkh.retail: debug